-- EffectsConduit::SoundGroupEx enum script
-- Friendly name: SoundGroups
-- auto-generated on 3/26/2013 at 10:36:19 AM by JBOSH
-- 
-- The following line instructs the dependency parser to ignore this file:
-- DependencyParser: IGNORE

SoundGroups = {}

SoundGroups["SOUND_GROUP_EX_MASTER"] = 0
SoundGroups["SOUND_GROUP_EX_SFX"] = 1
SoundGroups["SOUND_GROUP_EX_MUSIC"] = 2
SoundGroups["SOUND_GROUP_EX_DIALOGUE"] = 3
SoundGroups["SOUND_GROUP_EX_SFX_ENEMY_BOSS"] = 10004
SoundGroups["SOUND_GROUP_EX_SFX_HERO_CLANK_FOLEY"] = 10005
SoundGroups["SOUND_GROUP_EX_SFX_BREAKABLE"] = 10006
SoundGroups["SOUND_GROUP_EX_SFX_AMBIENT_3D"] = 10007
SoundGroups["SOUND_GROUP_EX_SFX_AMBIENT_2D"] = 10008
SoundGroups["SOUND_GROUP_EX_SFX_HERO_RATCHET_GEN"] = 10009
SoundGroups["SOUND_GROUP_EX_SFX_HERO_RATCHET_FOLEY"] = 10010
SoundGroups["SOUND_GROUP_EX_SFX_HERO_QWARK_WEAPON"] = 10011
SoundGroups["SOUND_GROUP_EX_SFX_HERO_QWARK_GEN"] = 10012
SoundGroups["SOUND_GROUP_EX_SFX_HERO_QWARK_FOLEY"] = 10013
SoundGroups["SOUND_GROUP_EX_SFX_HERO_NEF_WEAPON"] = 10014
SoundGroups["SOUND_GROUP_EX_SFX_HERO_NEF_GEN"] = 10015
SoundGroups["SOUND_GROUP_EX_SFX_HERO_ALL_WEAPON"] = 10016
SoundGroups["SOUND_GROUP_EX_SFX_HERO_ALL_GEN"] = 10017
SoundGroups["SOUND_GROUP_EX_SFX_HERO"] = 10018
SoundGroups["SOUND_GROUP_EX_SFX_EXTRA_LARGE"] = 10019
SoundGroups["SOUND_GROUP_EX_SFX_EXPLOSION_SMALL"] = 10020
SoundGroups["SOUND_GROUP_EX_SFX_EXPLOSION_BIG"] = 10021
SoundGroups["SOUND_GROUP_EX_SFX_ENEMY_WEAPON"] = 10022
SoundGroups["SOUND_GROUP_EX_SFX_ENEMY_GEN"] = 10023
SoundGroups["SOUND_GROUP_EX_SFX_HERO_CLANK_WEAPON"] = 10024
SoundGroups["SOUND_GROUP_EX_SFX_HERO_NEF_FOLEY"] = 10025
SoundGroups["SOUND_GROUP_EX_SFX_HERO_CLANK_GEN"] = 10026
SoundGroups["SOUND_GROUP_EX_DIAL_EXTRA_LARGE"] = 10027
SoundGroups["SOUND_GROUP_EX_DIAL_AMB_FX_WALLA"] = 10028
SoundGroups["SOUND_GROUP_EX_DIAL_VOC_FX_HERO"] = 10029
SoundGroups["SOUND_GROUP_EX_DIAL_VOC_FX_NPC_ENEMY"] = 10030
SoundGroups["SOUND_GROUP_EX_DIAL_VOC_FX"] = 10031
SoundGroups["SOUND_GROUP_EX_DIAL_TRIV_NPC"] = 10032
SoundGroups["SOUND_GROUP_EX_DIAL_TRIV_HERO"] = 10033
SoundGroups["SOUND_GROUP_EX_DIAL_TRIV"] = 10034
SoundGroups["SOUND_GROUP_EX_DIAL_STAND_NPC_ENEMY"] = 10035
SoundGroups["SOUND_GROUP_EX_DIAL_STAND_HERO"] = 10036
SoundGroups["SOUND_GROUP_EX_DIAL_STAND"] = 10037
SoundGroups["SOUND_GROUP_EX_DIAL_IMP_NPC_ENEMY"] = 10038
SoundGroups["SOUND_GROUP_EX_DIAL_IMP_HERO"] = 10039
SoundGroups["SOUND_GROUP_EX_DIAL_IMP"] = 10040
SoundGroups["SOUND_GROUP_EX_DIAL_CRIT_RADIO"] = 10041
SoundGroups["SOUND_GROUP_EX_DIAL_CRIT_NPC_ENEMY"] = 10042
SoundGroups["SOUND_GROUP_EX_DIAL_CRIT_HERO"] = 10043
SoundGroups["SOUND_GROUP_EX_DIAL_CRIT"] = 10044
SoundGroups["SOUND_GROUP_EX_MUS_REALTIME_MOVIE"] = 10045
SoundGroups["SOUND_GROUP_EX_MUS_3D_PRACTICAL"] = 10046
SoundGroups["SOUND_GROUP_EX_MUS_STINGER"] = 10047
SoundGroups["SOUND_GROUP_EX_MUS_HIGH_INTENSITY"] = 10048
SoundGroups["SOUND_GROUP_EX_MUS_MEDIUM_INTENSITY"] = 10049
SoundGroups["SOUND_GROUP_EX_MUS_LOW_INTENSITY"] = 10050
SoundGroups["SOUND_GROUP_EX_SFX_ENEMY_FOLEY"] = 10051
SoundGroups["SOUND_GROUP_EX_SFX_VEHICLE"] = 10052
SoundGroups["SOUND_GROUP_EX_SFX_SPECIAL"] = 10053
SoundGroups["SOUND_GROUP_EX_SFX_REALTIME_MOVIE"] = 10054
SoundGroups["SOUND_GROUP_EX_SFX_PROP"] = 10055
SoundGroups["SOUND_GROUP_EX_SFX_NPC_WEAPON"] = 10056
SoundGroups["SOUND_GROUP_EX_SFX_NPC_GEN"] = 10057
SoundGroups["SOUND_GROUP_EX_SFX_NPC_FOLEY"] = 10058
SoundGroups["SOUND_GROUP_EX_SFX_MECHANICAL"] = 10059
SoundGroups["SOUND_GROUP_EX_SFX_HUD"] = 10060
SoundGroups["SOUND_GROUP_EX_SFX_HERO_RATCHET_WEAPON"] = 10061

-- end EffectsConduit::SoundGroupEx dynamic enum script
